# Generated by Django 5.2.6 on 2025-09-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En ruta'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
