# Generated by Django 5.2.6 on 2025-10-07 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0002_vehiculo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
        migrations.AlterModelOptions(
            name='eventoenvio',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evento de Envío', 'verbose_name_plural': 'Eventos de Envío'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['-fecha'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['placa'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='alerta',
            name='atendida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='alerta',
            name='notas_atencion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='contacto_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='contacto_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='descripcion_carga',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='destino_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='destino_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_estimada_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='envio',
            name='telefono_destino',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='envio',
            name='telefono_origen',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='envio',
            name='valor_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='eventoenvio',
            name='bateria_dispositivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoenvio',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AddField(
            model_name='eventoenvio',
            name='tipo',
            field=models.CharField(choices=[('inicio', 'Inicio de Ruta'), ('checkpoint', 'Punto de Control'), ('parada', 'Parada'), ('incidente', 'Incidente'), ('entrega', 'Entrega')], default='checkpoint', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoenvio',
            name='velocidad_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sensor',
            name='valor_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='valor_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='proximo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('robo', 'Robo'), ('accidente', 'Accidente'), ('desvio', 'Desvío de ruta'), ('velocidad', 'Exceso de Velocidad'), ('parada_no_autorizada', 'Parada No Autorizada'), ('perdida_señal', 'Pérdida de Señal GPS'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('incidencia', 'Con Incidencia'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='envio',
            name='numero_guia',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='cargas.vehiculo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('vibracion', 'Vibración'), ('presion', 'Presión'), ('luz', 'Luz'), ('apertura', 'Apertura de Puerta')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('conductor', 'Conductor')], db_index=True, default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad_toneladas',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.OneToOneField(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculo_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En ruta'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], db_index=True, default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['numero_guia'], name='cargas_envi_numero__504b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='cargas_envi_estado_179a5a_idx'),
        ),
    ]
